# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180223_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
