# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20180223_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(null=True, to='photos.Location'),
        ),
    ]
